/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class SnakeGame {
    public String getGreeting() {
        return "Snake Application!";
    }

    public static void main(String[] args) {
        System.out.println(new SnakeGame().getGreeting());
    }
}
