package com.moormic;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.moormic.SnakeGame;
import org.junit.Test;
import static org.junit.Assert.*;

public class SnakeGameTest {

}
